### ISSUE TITLE
程序包android.support.annotation不存在 

### ISSUE THREAD

**Issue by lrxiang222** [qiuxiang/react-native-amap-geolocation#99]
**\geolocation\AMapGeolocationModule.java:3: 错误: 程序包android.support.annotation不存在**

React-Native版本：0.59.10
react-native-amap-geolocation版本：1.0.4

**Comment by 1442916418** [comment]
请问怎么解决？谢谢！

**Comment by cw0925** [comment]
同样的问题

**Comment by 1442916418** [comment]
暂未解决，请问有好的办法吗？


------------------ 原始邮件 ------------------
发件人: "cw0925"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 下午4:36
收件人: "qiuxiang/react-native-amap-geolocation"<react-native-amap-geolocation@noreply.github.com>;
抄送: "余水生"<1442916418@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qiuxiang/react-native-amap-geolocation] 程序包android.support.annotation不存在  (#99)




同样的问题

**Comment by cw0925** [comment]
<img width="756" alt="屏幕快照 2019-09-30 上午10 10 27" src="https://user-images.githubusercontent.com/17431906/65844910-ae310f00-e36a-11e9-9875-399cd32b6e93.png">
我是把那两句注释解决的，可以参考一下

**Comment by cricketsbrother** [comment]
我也是注释。。不知道有没有影响。但没有报错了

**Comment by lrxiang222** [comment]
这个是由于使用了Rn升级或者安装新的包，导致使用了androidx 集成而导致的问题，需要查一下是哪个包影响的，改下版本不使用androidx，还有就是要注意一下react-native-amap-geolocation的版本

**Comment by 1442916418** [comment]
好的，我再试试，谢谢回复！


------------------ 原始邮件 ------------------
发件人: "lrxiang"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 中午11:01
收件人: "qiuxiang/react-native-amap-geolocation"<react-native-amap-geolocation@noreply.github.com>;
抄送: "余水生"<1442916418@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qiuxiang/react-native-amap-geolocation] 程序包android.support.annotation不存在  (#99)




这个是由于使用了Rn升级或者安装新的包，导致使用了androidx 集成而导致的问题，需要查一下是哪个包影响的，改下版本不使用androidx，还有就是要注意一下react-native-amap-geolocation的版本

**Comment by xif3681** [comment]
> 这个是由于使用了Rn升级或者安装新的包，导致使用了androidx 集成而导致的问题，需要查一下是哪个包影响的，改下版本不使用androidx，还有就是要注意一下react-native-amap-geolocation的版本

![image](https://user-images.githubusercontent.com/13679380/66538990-2cef2e80-eb59-11e9-954c-11cfc530dfdd.png)
请问"react-native": "0.61.1",下哪个react-native-amap-geolocation的版本
我的版本是v1.0.4 也存在这个问题

**Comment by xif3681** [comment]
> 好的，我再试试，谢谢回复！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "lrxiang"<notifications@github.com>; 发送时间: 2019年10月10日(星期四) 中午11:01 收件人: "qiuxiang/react-native-amap-geolocation"<react-native-amap-geolocation@noreply.github.com>; 抄送: "余水生"<1442916418@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [qiuxiang/react-native-amap-geolocation] 程序包android.support.annotation不存在 (#99) 这个是由于使用了Rn升级或者安装新的包，导致使用了androidx 集成而导致的问题，需要查一下是哪个包影响的，改下版本不使用androidx，还有就是要注意一下react-native-amap-geolocation的版本 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

解决了吗？【关注】

**Comment by 1442916418** [comment]
未解决，我已放弃这个版本，重新拉取版本操作！




------------------ 原始邮件 ------------------
发件人: "Shuqi Luo"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 中午12:32
收件人: "qiuxiang/react-native-amap-geolocation"<react-native-amap-geolocation@noreply.github.com>;
抄送: "余水生"<1442916418@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qiuxiang/react-native-amap-geolocation] 程序包android.support.annotation不存在  (#99)



 
好的，我再试试，谢谢回复！
 …
 ------------------ 原始邮件 ------------------ 发件人: "lrxiang"notifications@github.com; 发送时间: 2019年10月10日(星期四) 中午11:01 收件人: "qiuxiang/react-native-amap-geolocation"react-native-amap-geolocation@noreply.github.com; 抄送: "余水生"1442916418@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [qiuxiang/react-native-amap-geolocation] 程序包android.support.annotation不存在 (#99) 这个是由于使用了Rn升级或者安装新的包，导致使用了androidx 集成而导致的问题，需要查一下是哪个包影响的，改下版本不使用androidx，还有就是要注意一下react-native-amap-geolocation的版本 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
解决了吗？【关注】

**Comment by lrxiang222** [comment]
https://www.jianshu.com/p/41de8689615d
这个可能对你们有所帮助，我使用的是 RN0.59.10的版本，很多的应用目前开始有部分兼容Androidx可以进行版本迁移，但是有的版本是不支持androix。目前这个应用，好像还没有完成androidx的迁移，所以你们可以问下作者或者更新下来，自行修改使之能够兼容到androidx

**Comment by yuanbolin** [comment]
试试将其自行修改到androidx

**Comment by Surile** [comment]
将`android.support.annotation`改成 `androidx.annotation`

**Comment by 1442916418** [comment]
谢谢回复



---原始邮件---
发件人: "夜雨"<notifications@github.com&gt;
发送时间: 2020年7月15日(周三) 晚上6:02
收件人: "qiuxiang/react-native-amap-geolocation"<react-native-amap-geolocation@noreply.github.com&gt;;
抄送: "1442916418"<1442916418@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [qiuxiang/react-native-amap-geolocation] 程序包android.support.annotation不存在  (#99)




 
将android.support.annotation改成 androidx.annotation
